### PR TITLE
Declare self-referencing functions with dict keyword

### PR DESCRIPTION
**Pull request by tpict**
Fix for #9 (see https://github.com/neovim/neovim/issues/5763)

### CODE REVIEW

**Comment by franciscoj** [comment]
I had the same issue when using https://github.com/janko-m/vim-test with the `dispatch` strategy and this patch also fixes the issue for me.

**Comment by jc00ke** [comment]
Would love to see this merged as I'm seeing this error too.

**Comment by jc00ke** [comment]
Thanks @radenling!

**Comment by radenling** [comment]
Merged! Thanks for the fix!

**Pull request merged**
